name: Telegram Bot CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Максимальное время выполнения (6 часов)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        cat << EOF > .env
        API_ID=${{ secrets.API_ID }}
        API_HASH=${{ secrets.API_HASH }}
        ADMIN_IDS=${{ secrets.ADMIN_IDS }}
        EOF
        
    - name: Run bot
      run: |
        python -m bot.bot
